"use client";
import {useEffect,useState} from "react";
import api from "@/utils/axiosIntance";
import {mensagemDeErroAdmin} from "@/lib/api/admin";
type Catalog={config:{chance_ppm:number;item_ids:number[]|null};receitas:{id:number;nome:string;raridade:string}[]};
export default function RecipeFindCard(){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[chance,setChance]=useState("0.1"),[all,setAll]=useState(true),[ids,setIds]=useState<number[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 function apply(data:Catalog){setCatalog(data);setChance(String(data.config.chance_ppm/10000));setAll(data.config.item_ids===null);setIds(data.config.item_ids?.filter(id=>data.receitas.some(r=>r.id===id))??data.receitas.map(r=>r.id));}
 useEffect(()=>{let active=true;api.get<{data:Catalog}>("/admin/expedition/recipes").then(r=>{if(active)apply(r.data.data);}).catch(e=>{if(active)setError(mensagemDeErroAdmin(e,"Não foi possível carregar as receitas."));});return()=>{active=false;};},[]);
 async function save(){setBusy(true);setError("");setMessage("");try{const percent=Number(chance.replace(",","."));if(!chance.trim()||!Number.isFinite(percent)||percent<0||percent>100||Math.abs(percent*10000-Math.round(percent*10000))>0.00001)throw Error("Use uma chance de 0 a 100%, com até quatro casas decimais.");const r=await api.put<{data:Catalog}>("/admin/expedition/recipes",{chance_ppm:Math.round(percent*10000),item_ids:all?null:ids});apply(r.data.data);setMessage("Chance e receitas salvas.");}catch(e){setError(mensagemDeErroAdmin(e,"Não foi possível salvar as receitas."));}finally{setBusy(false);}}
 return <section className="rounded-2xl border-2 border-[#F3B43F]/40 bg-[#292018]/80 p-5"><h2 className="font-imFeel text-2xl text-[#F3B43F]">Achado raro de receitas</h2><p className="mt-2 text-sm text-white/70">Sorteio adicional em qualquer região e profissão, após uma coleta não interrompida. A chance padrão de 0,1% é de encontrar uma receita; depois o jogo escolhe uma das receitas habilitadas com chances iguais. Não substitui o material normal e não usa os pesos de recursos.</p><label className="mt-4 block text-sm text-white">Chance de encontrar receita (%) <input aria-label="Chance de encontrar receita (%)" inputMode="decimal" value={chance} onChange={e=>setChance(e.target.value)} disabled={busy||!catalog} className="ml-2 w-28 rounded-lg border border-white/20 bg-black/30 px-2 py-1.5 text-base tabular-nums" /></label><label className="mt-3 flex gap-2 text-sm text-white"><input type="checkbox" checked={all} disabled={busy||!catalog} onChange={e=>setAll(e.target.checked)}/>Incluir todas as receitas ativas, inclusive novas</label><div className="mt-3 grid max-h-72 gap-2 overflow-y-auto sm:grid-cols-2">{catalog?.receitas.map(r=><label key={r.id} className="flex gap-2 text-sm text-white/80"><input type="checkbox" checked={all||ids.includes(r.id)} disabled={all||busy} onChange={e=>setIds(a=>e.target.checked?[...a,r.id]:a.filter(id=>id!==r.id))}/>{r.nome}</label>)}</div>{catalog&&!catalog.receitas.length&&<p className="mt-2 text-white/60">Nenhum item do tipo Receita ativo cadastrado.</p>}<p className="mt-3 text-sm text-white/60">Cadastre o item como Receita e vincule seu aprendizado no admin da Forja ou Alquimia. Não é necessário criar um recurso de coleta. Chance zero ou nenhuma receita selecionada desabilita o achado.</p>{error&&<p role="alert" className="mt-2 text-red-300">{error}</p>}{message&&<p role="status" className="mt-2 text-green-300">{message}</p>}<button type="button" onClick={save} disabled={busy||!catalog} className="mt-3 rounded-lg bg-[#BC8418] px-4 py-2 font-bold text-black disabled:opacity-50">{busy?"Salvando...":"Salvar achados de receitas"}</button></section>;
}
